config/routes.rb
Dev::Application.routes.draw do
  devise_for :users

  resources :organisations

    root :to => 'organisations#index'

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  attr_accessible :content, :name, :website_url
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable,:token_authenticatable#,:encryptable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  #before_save :ensure_authentication_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
before_filter :authenticate_user!, :except => [:show,:index]
  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisations }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
      else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find(params[:id])
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dev</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body >
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert"><%= alert %></p> 
<% end %>
<div class="span12">

<div id="user_nav" style="float:right">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Change your password", edit_user_registration_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
 </div>

 
      
<%= yield %>
</div>
</body>
</html>

app/views/organisations/_form.html.erb
<%= form_for(@organisation) do |f| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% @organisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :size => "35" %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br />
    <%= f.text_field :website_url %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<h1>Listing organisations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Website url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organisations.each do |organisation| %>
  <tr>
    <td><%= organisation.name %></td>
    <td><%= organisation.content %></td>
    <td><%= organisation.website_url %></td>
    <td><%= link_to 'Show', organisation %></td>
    <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
    <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render 'form' %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organisation.name %>
</p>

<p>
  <b>Content:</b>
  <%= @organisation.content %>
</p>

<p>
  <b>Website url:</b>
  <%= @organisation.website_url %>
</p>


<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>